### ISSUE TITLE
person always nil if :stream option not specified

### ISSUE THREAD

**Issue by dpasechnik** [clearbit/clearbit-ruby#18]
Clearbit::Enrichment.find(email: 'alex@alexmaccaw.com')

webhook result:
"body":{"person":null,"company":{"id":"41825e9a-8390-458c-a0e3-57fca7317392","name":"Alex MacCaw","legalName":null,"domain":"alexmaccaw.com","domainAliases":[],"url":"http://alexmaccaw.com","site":{"url":"http://alexmaccaw.com","title":"Alex MacCaw","h1":"Alex MacCaw","metaDescription":"JavaScript programmer, O'Reilly author, open source hacker","metaAuthor":"Alex MacCaw"},"category":{"sector":null,"industryGroup":null,"industry":null,"subIndustry":null},"tags":[],"description":"https://t.co/2Rm44uqoVU co-founder. Tea, Earl Grey, hot.","raised":null,"location":null,"geo":{"streetNumber":null,"streetName":null,"subPremise":null,"city":null,"postalCode":null,"state":null,"stateCode":null,"country":null,"countryCode":null,"lat":null,"lng":null},"employees":null,"logo":"https://logo.clearbit.com/alexmaccaw.com","google":{"rank":5},"alexa":{"usRank":271236,"globalRank":500558},"facebook":{"handle":null,"likes":null},"linkedin":{"handle":null},"twitter":{"handle":"maccaw","id":"2006261","bio":"https://t.co/2Rm44uqoVU co-founder. Tea, Earl Grey, hot.","followers":16646,"following":1954,"location":"San Francisco","site":"https://t.co/lBoBBpfLBK","avatar":"https://pbs.twimg.com/profile_images/658880981017882629/nlXSOJnc_normal.jpg"},"angellist":{"id":null,"handle":null,"description":null,"followers":null,"blogUrl":null},"crunchbase":{"handle":null},"emailProvider":false,"type":"private","ticker":null,"phone":null}},"status":200,"type":"person_company","id":null}

Clearbit::Enrichment::Person.find(email: 'alex@alexmaccaw.com')

webhook result:

{"body":null,"status":404,"type":"person","id":null}

**Comment by robholland** [comment]
Please try this again, the issue was a blip in our API rather than a binding issue.
