### ISSUE TITLE
Missing tags for recent releases?

### ISSUE THREAD

**Issue by andreynering** [clearbit/clearbit-ruby#35]
While the most recent release is v0.3.1, the most recent tag is v0.2.8.

It'd be nice to add the missing tags to the right released commits to avoid confusion.

**Comment by croaky** [comment]
I’m also looking for the v0.3.1 tag to compare against v0.3.2. Dependabot opened an automatic pull request on our repo but it’s hard to see the changes in compare view without the tag.

**Comment by tristandunn** [comment]
Added the missing [v0.3.0](https://github.com/clearbit/clearbit-ruby/tree/v0.3.0) and [v0.3.1](https://github.com/clearbit/clearbit-ruby/tree/v0.3.1) tags.

**Comment by croaky** [comment]
Thanks, @tristandunn!
